---
- name: Create and start EC2 instances
  hosts: localhost
  tasks:
    - name: Launch instances with proper configuration
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        key_name: vockey
        instance_type: t4g.nano
        image_id: ami-0325498274077fac5
        network_interfaces:
          - device_index: 0
            subnet_id: subnet-089e7e73167c18063
            groups:
              - sg-04443f5c77aada560  # Vérifiez que ce SG est dans le même VPC que le subnet
            assign_public_ip: true
        tags:
          Name: "{{ item }}"
          Environment: Testing
        filters:  # Ajout d'un filtre pour vérifier les instances existantes
          "tag:Name": "{{ item }}"
          instance-state-name: [running, stopped, pending]
        wait: yes
        state: present  # Crée seulement si l'instance n'existe pas déjà
      loop:
        - mavm
        - totovm
        - zefvm