- name: Install Apache web server
  hosts: all
  become: true  # Exécution en tant que root
  vars:
    php_version: "8.3"  # Ajout des guillemets pour éviter les erreurs d'interprétation
  tasks:
    - name: Install Apache and PHP
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - apache2
        - "php{{ php_version }}"
      when: ansible_facts['os_family'] == "Debian"

    - name: Ensure Apache is running and enabled
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
      when: ansible_facts['os_family'] == "Debian"
      